title: Northern Woods Construction
logo: "/images/nwc150.jpg?raw=true"
description: > 
  <br><br><br>
  Experts in concrete forming for water retaining structures, with over 40 years of experience. 
  <br><br>
  Specializing in water reservoirs and water and wastewater treatment plants.
  <br><br>
  Based in BC, Canada
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-23751TSL3B
